name: Build Geode Mod

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: iOS
          os: macos-latest
          target: iOS

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      # Исправляем окружение: ставим стабильный Xcode для iOS сборки
      - name: Set up Xcode version
        if: matrix.config.target == 'iOS'
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Build the mod
        # Используем версию экшена за 10 августа
        uses: geode-sdk/build-geode-mod@d0b5030d7ea2d46e302061e8eb87353f46f05b8a
        with:
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Combine builds
        # Склейку тоже фиксируем на коммите от 10 августа
        uses: geode-sdk/build-geode-mod/combine@d0b5030d7ea2d46e302061e8eb87353f46f05b8a
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
